### PR TITLE
fix: Add liveness and readiness probes

### LINKED ISSUE #334: Controller should include readiness/liveness checks in deployments
I don't believe the controller includes readiness/lives checks on any of the deployments which seems important. We are having a production issue where lookout stops accepting TCP connections and this would likely have been discovered by a liveness check. 

I should have a pull request up in the next week to add support for this.

### PR DESCRIPTION
**Pull request by Sovietaced**
## Description

The pull request updates various controllers to add readiness & liveness probes to containers where applicable. These probes should help indicate when it is safe to cutover to new deployments. 

I cross referenced https://github.com/armadaproject/armada/tree/master/deployment (I may have found some bugs in here tho) as well as each application's config structs to understand which ports they expose. 

Fixes #334 

## Type of change

Please select the type of change your PR introduces:

- [x] Bugfix
- [x] Feature
- [ ] Code Style Update (formatting, renaming)
- [ ] Refactor (code changes that do not fix a bug or add a feature)
- [ ] Documentation Update
- [ ] Other (please describe):

## How Has This Been Tested?
Added unit tests to assert the fully generated deployment with probes. 

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my code.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

File: internal/controller/install/armadaserver_controller.go [hunk 1]
```diff
@@ -678,3 +687,21 @@ func createServerPrometheusRule(server *installv1alpha1.ArmadaServer) *monitorin
 		},
 	}
 }
+
+type ArmadaServerConfig struct {
```
Comment (dejanzele) [inline internal/controller/install/armadaserver_controller.go:691]: Can you reuse the `CommonApplicationConfig` as it already contains the `grpc` configuration block?
As currently this defines component-specific config structs which have a common field.

Here is the struct - https://github.com/armadaproject/armada-operator/blob/9e41715dd4bbae49d68d2c49a7961a36d32d2561/internal/controller/builders/config.go#L16

Comment (Sovietaced) [reply internal/controller/install/armadaserver_controller.go:691]: Definitely. I did not see that

File: internal/controller/install/executor_controller.go [hunk 2]
```diff
@@ -274,10 +275,12 @@ func (r *ExecutorReconciler) createDeployment(
 		ImagePullPolicy: corev1.PullIfNotPresent,
 		Image:           ImageString(executor.Spec.Image),
 		Args:            []string{appConfigFlag, appConfigFilepath},
-		Ports:           newContainerPortsMetrics(config),
+		Ports:           newContainerPortsHTTPWithMetrics(config),
```
Comment (Sovietaced) [inline internal/controller/install/executor_controller.go:278]: This is a bug fix since the executor does have an HTTP server..

File: internal/controller/install/scheduler_controller.go [hunk 3]
```diff
@@ -314,10 +315,12 @@ func newSchedulerDeployment(
 						ImagePullPolicy: corev1.PullIfNotPresent,
 						Image:           ImageString(scheduler.Spec.Image),
 						Args:            []string{"run", appConfigFlag, appConfigFilepath},
-						Ports:           newContainerPortsGRPCWithMetrics(config),
+						Ports:           newContainerPortsAll(config),
```
Comment (Sovietaced) [inline internal/controller/install/scheduler_controller.go:318]: Another bug fix since the scheduler has all the ports.

File: internal/controller/install/binoculars_controller_test.go [hunk 4]
```diff
@@ -476,12 +481,12 @@ func TestSchedulerReconciler_createBinocularsIngress(t *testing.T) {
 
 	input := v1alpha1.Binoculars{
 		TypeMeta: metav1.TypeMeta{
-			Kind:       "Lookout",
+			Kind:       "binoculars",
```
Comment (Sovietaced) [inline internal/controller/install/binoculars_controller_test.go:484]: small bug fix

File: internal/controller/install/armadaserver_controller_test.go [hunk 5]
```diff
@@ -429,12 +433,12 @@ func TestSchedulerReconciler_createIngress(t *testing.T) {
 
 	input := v1alpha1.ArmadaServer{
 		TypeMeta: metav1.TypeMeta{
-			Kind:       "Lookout",
+			Kind:       "armadaserver",
```
Comment (Sovietaced) [inline internal/controller/install/armadaserver_controller_test.go:436]: typo fix?

File: internal/controller/install/common_helpers.go [hunk 6]
```diff
@@ -371,6 +380,36 @@ func createEnv(crdEnv []corev1.EnvVar) []corev1.EnvVar {
 	return envVars
 }
 
+func CreateProbesWithScheme(scheme corev1.URIScheme) (*corev1.Probe, *corev1.Probe) {
```
Comment (Sovietaced) [inline internal/controller/install/common_helpers.go:383]: The values here are pretty standardized for now but we might want to support customization later.

File: internal/controller/install/common_helpers.go [hunk 7]
```diff
@@ -317,7 +317,16 @@ func ExtractPulsarConfig(config runtime.RawExtension) (PulsarConfig, error) {
 	if err != nil {
 		return PulsarConfig{}, err
 	}
-	return asConfig.Pulsar, nil
+	return asConfig.Pulsar, err
```
Comment (dejanzele) [inline internal/controller/install/common_helpers.go:320]: is there a need to return `err` as it will 100% be `nil`?

File: internal/controller/install/common_helpers.go (hunk 6 above)
Comment (dejanzele) [reply internal/controller/install/common_helpers.go:383]: Yeah, seems good enough for starters.

File: internal/controller/install/armadaserver_controller_test.go (hunk 5 above)
Comment (dejanzele) [reply internal/controller/install/armadaserver_controller_test.go:436]: Yep, good catch, can you also please capitalize it? All k8s Kinds start with a capital letters.

File: internal/controller/install/binoculars_controller_test.go (hunk 4 above)
Comment (Sovietaced) [reply internal/controller/install/binoculars_controller_test.go:484]: Sure

File: internal/controller/install/common_helpers.go (hunk 7 above)
Comment (Sovietaced) [reply internal/controller/install/common_helpers.go:320]: No I can change that

**Review by dejanzele — APPROVED** [review]
